### ISSUE TITLE
CovidMetrics-epiBATS (move from German ForecastHub to automated European ForecastHub)

### ISSUE THREAD

**Issue by arodloff** [covid19-forecast-hub-europe/covid19-forecast-hub-europe-submissions#15]
### URL of the public git repository
https://github.com/arodloff/autosubmission-CovidMetrics-epiBATS.git

### When should the automated workflow run (UTC timezone)?

Monday 10:00 UCT

### Name of the responsible GitHub user

arodloff

**Comment by Bisaloo** [comment]
Thanks, great to have you on board!

I have added your model in 64f301e8dad30798cd7d448f87cd8a97842f7f6e & bcd9f8502ba9f47c64c05e6ea1a76f1f186ef58b.

You can see a test submission in https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/pull/2184. Tests are failing but it seems only related to the fact it was submitted on a Friday.

**Comment by Bisaloo** [comment]
@arodloff, I see you have pushed a fix for the date issue earlier this week. Thanks for this! 

For your information, updates are not automatically picked up by the auto-submission framework. For security reasons, I have to explicitly pull your changes so please ping me if you ever need to do an update :wink:

**Comment by arodloff** [comment]
Thanks for the help! Is the fix you mentioned taken care of, or do I need to do something for it to be recognized by the auto-submission framework?

**Comment by Bisaloo** [comment]
No, all good, don't worry. I pulled the fix in 24b2dafef69d8ab8d8136d56dd2963e7ca5b4a76.

I was just mentioning it here for future situations. It's easy for me to miss commits in your repo so if you want to update something, you should ping me so I pull your changes.
