### ISSUE TITLE
Weekly growth scheduled run failure

### ISSUE THREAD

**Issue by seabbs** [covid19-forecast-hub-europe/covid19-forecast-hub-europe-submissions#4]
I see a failure in the GitHub action for the weekly growth model. From a skim, it looks unrelated (??) to the model itself and to be an issue with the `renv` setup action. Is there something I can do to fix or something else I should do (like use the action in the weekly growth repo to generate a forecast and submit it?)

https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe-submissions/actions/runs/1646204465

**Comment by Bisaloo** [comment]
That was a very simple mistake from my end: https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe-submissions/commit/0b6efcc336647d09312d9aaa101eee56b441b436. Sorry about this, I shouldn't have tried to do it in 2 min while still on leave.
